### ISSUE TITLE
Executing negotiation example in Advanced Schedd Interactions kills the Jupyter kernel

### ISSUE THREAD

**Issue by JoshKarpel** [htcondor/htcondor-python-bindings-tutorials#11]
Executing the Advanced Schedd Interactions tutorial from scratch via "Restart Kernel and Run All Cells" results in the kernel dying:

![image](https://user-images.githubusercontent.com/7133863/75179671-35a76200-5700-11ea-95a5-a03cfe1eb6b7.png)

Turning on `htcondor.enable_debug()` just before running the last two cells (the ones in the negotiation section) results in
```
02/24/20 18:23:02 Can't open directory "/etc/condor/passwords.d" as PRIV_UNKNOWN, errno: 2 (No such file or directory)
02/24/20 18:23:02 Can't open directory "/etc/condor/passwords.d" as PRIV_UNKNOWN, errno: 2 (No such file or directory)
02/24/20 18:23:02 condor_write(): Socket closed when trying to write 21 bytes to schedd at <172.17.0.2:9618>, fd is 45
02/24/20 18:23:02 Buf::write(): condor_write() failed
```

Jupyter itself is not passing through any exceptions or log messages, which makes me think we might be seeing an underlying segfault.

The bindings code in question is roughly

```python
import htcondor

htcondor.enable_debug()

coll = htcondor.Collector()
private_ads = coll.query(htcondor.AdTypes.StartdPrivate)
startd_ads = coll.query(htcondor.AdTypes.Startd)
claim_ads = []
for ad in startd_ads:
    if "Name" not in ad: continue
    found_private = False
    for pvt_ad in private_ads:
        if pvt_ad.get('Name') == ad['Name']:
            found_private = True
            ad['ClaimId'] = pvt_ad['Capability']
            claim_ads.append(ad)

with htcondor.Schedd().negotiate("bbockelm@unl.edu") as session:
    found_claim = False
    for resource_request in session:
        for claim_ad in claim_ads:
            if resource_request.symmetricMatch(claim_ad):
                print("Sending claim for", claim_ad["Name"])
                session.sendClaim(claim_ads[0])
                found_claim = True
                break
        if found_claim: break
```

**Comment by bbockelm** [comment]
@JoshKarpel - is there any knowledge in the `MasterLog`?

**Comment by JoshKarpel** [comment]
A little more information...

Nothing suspicious in the `MasterLog`, but these lines appear in the `SchedLog` right after firing the last cell in the notebook:
```
02/25/20 14:51:42 (pid:26) Using negotiation protocol: NEGOTIATE
02/25/20 14:51:42 (pid:26) Remote negotiator (host=172.17.0.2, pool=) is trying to negotiate with submitter bbockelm@unl.edu; that submitter was not sent to the negotiator, so aborting the negotiation attempt.
```

One time when running this, I got this error:
```
Exception in callback BaseAsyncIOLoop._handle_events(24, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(24, 1)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 138, in _handle_events
    handler_func(fileobj, events)
  File "/opt/conda/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_events
    self._rebuild_io_state()
  File "/opt/conda/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 522, in _rebuild_io_state
    self._update_handler(state)
  File "/opt/conda/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 542, in _update_handler
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/opt/conda/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 176, in add_callback
    call_soon(self._run_callback, functools.partial(callback, *args, **kwargs))
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 687, in call_soon
    handle = self._call_soon(callback, args, context)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 703, in _call_soon
    handle = events.Handle(callback, args, self, context)
  File "/opt/conda/lib/python3.7/asyncio/events.py", line 48, in __init__
    if self._loop.get_debug():
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'get_debug'
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-14-8eb74e178cb8> in <module>
      2     found_claim = False
----> 3     for resource_request in session:
      4         for claim_ad in claim_ads:

SystemError: <Boost.Python.function object at 0x564344c4c830> returned NULL without setting an error

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-14-8eb74e178cb8> in <module>
      8                 found_claim = True
      9                 break
---> 10         if found_claim: break

RuntimeError: Could not send END_NEGOTIATE to remote schedd.
```
It seems to be the root cause, but I can't get Jupyter to display it consistently (perhaps some kind of timing issue with the kernel sending messages?).

Running the extracted script above outside of a notebook results in
```
02/25/20 14:54:53 Can't open directory "/etc/condor/passwords.d" as PRIV_UNKNOWN, errno: 2 (No such file or directory)
02/25/20 14:54:53 Can't open directory "/home/jovyan/.condor/tokens.d" as PRIV_UNKNOWN, errno: 2 (No such file or directory)
02/25/20 14:54:53 Can't open directory "/etc/condor/passwords.d" as PRIV_UNKNOWN, errno: 2 (No such file or directory)
02/25/20 14:54:53 condor_read(): Socket closed abnormally when trying to read 5 bytes from schedd at <172.17.0.2:9618>, errno=104 Connection reset by peer
Segmentation fault (core dumped)
```
Here's the stack trace from `gdb`:
```
Program received signal SIGSEGV, Segmentation fault.
_PyErr_GetTopmostException (tstate=0x0) at /tmp/build/80754af9/python_1565725737370/work/Python/errors.c:59
59	/tmp/build/80754af9/python_1565725737370/work/Python/errors.c: No such file or directory.
(gdb) bt
#0  _PyErr_GetTopmostException (tstate=0x0) at /tmp/build/80754af9/python_1565725737370/work/Python/errors.c:59
#1  0x00005594e05dbeaf in PyErr_SetObject () at /tmp/build/80754af9/python_1565725737370/work/Python/errors.c:98
#2  0x00005594e05e2141 in PyErr_SetString () at /tmp/build/80754af9/python_1565725737370/work/Python/errors.c:170
#3  0x00007f9b05c8372d in RequestIterator::getNextRequest (this=0x5594e1640490) at /var/lib/condor/execute/slot1/dir_26216/htcondor_source/src/python-bindings/schedd.cpp:368
#4  RequestIterator::next (this=0x5594e1640490) at /var/lib/condor/execute/slot1/dir_26216/htcondor_source/src/python-bindings/schedd.cpp:390
#5  0x00007f9b05c86cbe in boost::python::detail::invoke<boost::python::to_python_value<boost::shared_ptr<ClassAdWrapper> const&>, boost::shared_ptr<ClassAdWrapper> (RequestIterator::*)(), boost::python::arg_from_python<RequestIterator&> > (rc=..., tc=<synthetic pointer>..., f=<optimized out>)
    at /var/lib/condor/execute/slot1/dir_26216/htcondor_pypi_build/bld_external/boost-1.66.0-p1/install/include/boost/python/detail/invoke.hpp:86
#6  boost::python::detail::caller_arity<1u>::impl<boost::shared_ptr<ClassAdWrapper> (RequestIterator::*)(), boost::python::default_call_policies, boost::mpl::vector2<boost::shared_ptr<ClassAdWrapper>, RequestIterator&> >::operator() (args_=<optimized out>, this=<optimized out>) at /var/lib/condor/execute/slot1/dir_26216/htcondor_pypi_build/bld_external/boost-1.66.0-p1/install/include/boost/python/detail/caller.hpp:221
#7  boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::shared_ptr<ClassAdWrapper> (RequestIterator::*)(), boost::python::default_call_policies, boost::mpl::vector2<boost::shared_ptr<ClassAdWrapper>, RequestIterator&> > >::operator() (this=<optimized out>, args=<optimized out>, kw=<optimized out>)
    at /var/lib/condor/execute/slot1/dir_26216/htcondor_pypi_build/bld_external/boost-1.66.0-p1/install/include/boost/python/object/py_function.hpp:38
#8  0x00007f9b05929eaa in boost::python::objects::function::call(_object*, _object*) const () from /opt/conda/lib/python3.7/site-packages/htcondor/../htcondor.libs/libpyclassad3-23c36fdd.7_8_9_5_wheel.so
#9  0x00007f9b0592a218 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from /opt/conda/lib/python3.7/site-packages/htcondor/../htcondor.libs/libpyclassad3-23c36fdd.7_8_9_5_wheel.so
#10 0x00007f9b059247d3 in boost::python::handle_exception_impl(boost::function0<void>) () from /opt/conda/lib/python3.7/site-packages/htcondor/../htcondor.libs/libpyclassad3-23c36fdd.7_8_9_5_wheel.so
#11 0x00007f9b05928b23 in function_call () from /opt/conda/lib/python3.7/site-packages/htcondor/../htcondor.libs/libpyclassad3-23c36fdd.7_8_9_5_wheel.so
#12 0x00005594e05caa3f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:125
#13 0x00005594e05e8e53 in _PyObject_Call_Prepend () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:908
#14 0x00005594e05caa3f in _PyObject_FastCallDict () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:125
#15 0x00005594e06210ea in call_unbound (nargs=0, args=0x0, self=0x7f9aff9e5d50, func=0x7f9b0792b320, unbound=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/typeobject.c:1506
#16 call_method (nargs=0, args=0x0, name=0x5594e07e2860 <PyId___next__.15090>, obj=0x7f9aff9e5d50) at /tmp/build/80754af9/python_1565725737370/work/Objects/typeobject.c:1535
#17 slot_tp_iternext () at /tmp/build/80754af9/python_1565725737370/work/Objects/typeobject.c:6578
#18 0x00005594e0680e36 in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:2809
#19 0x00005594e05c9539 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
#20 0x00005594e05ca424 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3959
#21 0x00005594e05ca44c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:524
#22 0x00005594e06dfb74 in run_mod () at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:1035
#23 0x00005594e06e9eb1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:988
#24 0x00005594e06ea0a3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1565725737370/work/Python/pythonrun.c:429
#25 0x00005594e06eb195 in pymain_run_file (p_cf=0x7ffecfc34590, filename=0x5594e14cd700 L"test.py", fp=0x5594e1513480) at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:433
#26 pymain_run_filename (cf=0x7ffecfc34590, pymain=0x7ffecfc346a0) at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:1612
#27 pymain_run_python (pymain=0x7ffecfc346a0) at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:2873
#28 pymain_main () at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3413
#29 0x00005594e06eb2bc in _Py_UnixMain () at /tmp/build/80754af9/python_1565725737370/work/Modules/main.c:3448
#30 0x00007f9b08302b97 in __libc_start_main (main=0x5594e05aa6c0 <main>, argc=2, argv=0x7ffecfc347f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffecfc347e8)
    at ../csu/libc-start.c:310
#31 0x00005594e0690062 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

Regardless of the situation we shouldn't be seg faulting. Looks like we're getting into a situation where Boost expects us to have raised an exception, but we didn't, so it explodes.

**Comment by JoshKarpel** [comment]
Sent upstream as https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=7524

**Comment by JoshKarpel** [comment]
Temporarily resolved by removing the examples in https://github.com/htcondor/htcondor-python-bindings-tutorials/commit/19c3ee296ae7c8ad397e0ca0d243455b238d4735, pending the upstream ticket.

**Comment by JoshKarpel** [comment]
It's looking like we're going to deprecate this instead of fixing it.
